### ISSUE TITLE
Missing explore loss?

### ISSUE THREAD

**Issue by SigmaBM** [Jiwonjeon9603/MASER#2]
explore_loss_subset in [maser_q_learner.py](https://github.com/Jiwonjeon9603/MASER/blob/main/learners/maser_q_learner.py), i.e., episodic correction losses in paper.

**Comment by Jiwonjeon9603** [comment]
Hi, sorry for the late reply!

I'm sorry, and my code was the old version.

Thanks for letting me know, and I updated explore loss in my code.

If there exists more issues, please let me know :)

**Comment by SigmaBM** [comment]
Thank you for the update!

Now the exploration loss is calculated using **target** q value, so the gradient won't propagate to q function. Actually, I ran the new released code and found it showed the same result as the old code. Should target q value here be q value from mac_out?
