### ISSUE TITLE
battle won mean always be 0

### ISSUE THREAD

**Issue by issuey** [Jiwonjeon9603/MASER#4]
I use the command like the instrument shows:
![image](https://user-images.githubusercontent.com/74280544/234577664-3fc3e301-51e4-4329-b973-8aa19002e41c.png)

but the battle won mean always be 0
![WS0)8V{B)X~D@(RME3K`AZF](https://user-images.githubusercontent.com/74280544/234577452-4feb17f9-b114-4045-b8a3-e272714ff9fc.jpg)

why this happen?

**Comment by Jiwonjeon9603** [comment]
Did you set the StarCraft environment reward setting for sparse_reward=True?

As you can see in my paper, I used a semi-sparse reward different from the SC2 environment's sparse_reward.
