### ISSUE TITLE
Meaning of block-wise operation in the paper?

### ISSUE THREAD

**Issue by RZ-Q** [Jiwonjeon9603/MASER#6]
I am confused about the block-wise operation, why the length is the same as the episode's length, and why to use this block-wise operation.

**Comment by Jiwonjeon9603** [comment]
Our algorithm is based on dqn which chooses episodes from experience replay buffer randomly. Therefore, the length which randomly chosen from experience replay buffer are the same length as the episode length. If you see the equations from our paper, you would understand this concept easily.
